//
//  RiveCodeSnippetGenerator.swift
//  RiveTestApp
//
//  Generates a self-contained SwiftUI embed snippet for a single CatalogItem, so a developer
//  unfamiliar with Rive can drop one file into their app and get a working, fully wired-up
//  animation (data binding, triggers, images) with no dependency on the rest of this app.
//

import Foundation

enum RiveCodeSnippetGenerator {
    /// The suggested `.swift` file name for the generated snippet (matches the type name inside).
    static func fileName(for item: CatalogItem) -> String {
        "\(swiftTypeName(for: item.src)).swift"
    }

    /// Generates the full contents of a `.swift` file embedding `item`.
    static func generate(for item: CatalogItem) -> String {
        let typeName = swiftTypeName(for: item.src)
        var lines: [String] = []

        // MARK: Header

        lines.append("//")
        lines.append("//  \(typeName).swift")
        lines.append("//  Generated by RiveTestApp — self-contained embed for \"\(item.src).riv\".")
        lines.append("//")
        lines.append("//  Artboard: \(item.artboardName ?? "(file default)")")
        lines.append("//  State machine: \(item.stateMachineName)")
        if let trigger = item.trigger {
            lines.append("//  Trigger: \(trigger)")
        }
        if let note = item.note, !note.isEmpty {
            lines.append("//  Note: \(note)")
        }
        if RiveLoader.previewSource(for: item) != nil {
            lines.append("//  This item also has a preview source in the catalog — duplicate the loader below")
            lines.append("//  with artboard \"preview\" (or the \"\(item.src)_preview.riv\" file) if you need it too.")
        }
        lines.append("//")
        lines.append("//  Usage: add \"\(item.src).riv\" to your app target's bundle resources, drop this file")
        lines.append("//  in alongside it, then embed with `\(typeName)()` anywhere in your view hierarchy.")
        lines.append("//")
        lines.append("")
        lines.append("import SwiftUI")
        lines.append("import RiveRuntime")
        lines.append("")

        // MARK: View

        lines.append("struct \(typeName): View {")
        lines.append("    @State private var rive: Rive?")
        lines.append("    @State private var worker: Worker?")
        lines.append("")
        lines.append("    var body: some View {")
        lines.append("        RiveUIViewRepresentable(rive: rive)")
        lines.append("            .task { await load() }")
        lines.append("    }")
        lines.append("")
        lines.append("    private func load() async {")
        lines.append("        guard rive == nil else { return }")
        lines.append("        do {")
        lines.append("            // A `Worker` runs Rive's rendering/data work off the main thread. In a real app,")
        lines.append("            // share a single `Worker` across all your Rive views instead of one per view.")
        lines.append("            let worker = try await Worker()")
        lines.append("            self.worker = worker")
        lines.append("            guard let url = Bundle.main.url(forResource: \"\(item.src)\", withExtension: \"riv\") else {")
        lines.append("                print(\"\(item.src).riv not found in the app bundle\")")
        lines.append("                return")
        lines.append("            }")
        lines.append("            let data = try Data(contentsOf: url)")
        lines.append("            let file = try await File(source: .data(data), worker: worker)")
        let artboardArg = item.artboardName.map { "\"\($0)\"" } ?? "nil"
        lines.append("            let artboard = try await file.createArtboard(\(artboardArg))")
        lines.append("            let stateMachine = try await artboard.createStateMachine(\"\(item.stateMachineName)\")")
        lines.append("            // `dataBind: .auto` resolves the artboard's default ViewModel instance, which is")
        lines.append("            // what every property binding below reads/writes.")
        lines.append("            let loaded = try await Rive(file: file, artboard: artboard, stateMachine: stateMachine, dataBind: .auto)")
        lines.append("            rive = loaded")
        lines.append("            applyInitialValues(to: loaded)")
        lines.append("        } catch {")
        lines.append("            print(\"Failed to load \(item.src).riv: \\(error)\")")
        lines.append("        }")
        lines.append("    }")

        // MARK: Initial values

        lines.append("")
        lines.append("    /// Sets every declared input to its default value once the animation has loaded.")
        lines.append("    private func applyInitialValues(to rive: Rive) {")
        lines.append("        guard let vmi = rive.viewModelInstance else { return }")
        if item.inputs.isEmpty {
            lines.append("        // No bindable parameters declared for this animation.")
        }
        for input in item.inputs {
            switch input {
            case .number(let name, let defaultValue):
                lines.append("        // Number property \"\(name)\"")
                lines.append("        vmi.setValue(of: NumberProperty(path: \"\(name)\"), to: \(numberLiteral(defaultValue ?? 0)))")
            case .boolean(let name, let defaultValue):
                lines.append("        // Boolean property \"\(name)\"")
                lines.append("        vmi.setValue(of: BoolProperty(path: \"\(name)\"), to: \(defaultValue ?? false))")
            case .string(let name, let defaultValue):
                lines.append("        // String property \"\(name)\"")
                lines.append("        vmi.setValue(of: StringProperty(path: \"\(name)\"), to: \"\(escaped(defaultValue ?? ""))\")")
            case .color(let name, let defaultValue):
                let comps = colorComponents(hex: defaultValue)
                lines.append("        // Color property \"\(name)\"")
                lines.append("        vmi.setValue(of: ColorProperty(path: \"\(name)\"), to: RiveRuntime.Color(red: \(comps.r), green: \(comps.g), blue: \(comps.b), alpha: \(comps.a)))")
            case .image(let name, _):
                lines.append("        // Image property \"\(name)\" — call set\(sanitizedIdentifier(name))Image(_:) below once you have the image data.")
            case .list(let name, let innerType, let innerName):
                lines.append("        // List property \"\(name)\" (items: \(innerType):\(innerName)) — use appendInstance/")
                lines.append("        // insertInstance with a nested ViewModelInstance if you need to populate this list.")
            }
        }
        lines.append("    }")

        // MARK: Trigger

        if let trigger = item.trigger {
            lines.append("")
            lines.append("    /// Fires the \"\(trigger)\" trigger.")
            lines.append("    func fire\(sanitizedIdentifier(trigger))() {")
            lines.append("        guard let vmi = rive?.viewModelInstance else { return }")
            lines.append("        vmi.fire(trigger: TriggerProperty(path: \"\(trigger)\"))")
            lines.append("    }")
        }

        // MARK: Image setters

        for input in item.inputs {
            guard case .image(let name, _) = input else { continue }
            lines.append("")
            lines.append("    /// Decodes `data` (e.g. PNG/JPEG bytes) and assigns it to the \"\(name)\" image property.")
            lines.append("    func set\(sanitizedIdentifier(name))Image(_ data: Data) {")
            lines.append("        guard let vmi = rive?.viewModelInstance, let worker else { return }")
            lines.append("        Task {")
            lines.append("            guard let image = try? await worker.decodeImage(from: data) else { return }")
            lines.append("            vmi.setValue(of: ImageProperty(path: \"\(name)\"), to: image)")
            lines.append("        }")
            lines.append("    }")
        }

        lines.append("}")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    /// Builds a PascalCase Swift type name from a `.riv` file name, e.g.
    /// `bannerparticlesbutton_v1` -> `BannerparticlesbuttonV1RiveView`.
    private static func swiftTypeName(for src: String) -> String {
        let parts = src
            .replacingOccurrences(of: "-", with: "_")
            .split(separator: "_")
            .map { $0.prefix(1).uppercased() + $0.dropFirst() }
        var base = parts.joined()
        if base.isEmpty { base = "Animation" }
        if let first = base.first, first.isNumber { base = "Rive" + base }
        return base + "RiveView"
    }

    /// Builds a valid, capitalized Swift identifier fragment from an arbitrary Rive property name
    /// (used to suffix generated function names like `fire<Name>()`/`set<Name>Image(_:)`).
    private static func sanitizedIdentifier(_ name: String) -> String {
        let cleaned = name.filter { $0.isLetter || $0.isNumber }
        guard !cleaned.isEmpty else { return "Property" }
        if let first = cleaned.first, first.isNumber { return "Property" + cleaned }
        return cleaned.prefix(1).uppercased() + cleaned.dropFirst()
    }

    private static func numberLiteral(_ value: Double) -> String {
        if value == value.rounded() && abs(value) < 1e15 {
            return String(format: "%.1f", value)
        }
        return String(value)
    }

    private static func escaped(_ value: String) -> String {
        value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
    }

    /// Parses a `#RRGGBB`/`#RRGGBBAA` hex string (matching `SwiftUI.Color(hex:)` in
    /// `RiveColor+SwiftUI.swift`) into 0-255 components; falls back to opaque white when the
    /// CSV didn't specify a default (deterministic, unlike the app's own random-default behavior).
    private static func colorComponents(hex: String?) -> (r: Int, g: Int, b: Int, a: Int) {
        guard var hex = hex?.trimmingCharacters(in: .whitespaces), !hex.isEmpty else {
            return (255, 255, 255, 255)
        }
        if hex.hasPrefix("#") { hex.removeFirst() }
        guard hex.count == 6 || hex.count == 8, let value = UInt64(hex, radix: 16) else {
            return (255, 255, 255, 255)
        }
        let hasAlpha = hex.count == 8
        let r = Int((value >> (hasAlpha ? 24 : 16)) & 0xFF)
        let g = Int((value >> (hasAlpha ? 16 : 8)) & 0xFF)
        let b = Int((value >> (hasAlpha ? 8 : 0)) & 0xFF)
        let a = hasAlpha ? Int(value & 0xFF) : 255
        return (r, g, b, a)
    }
}
